name: Build WASM

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v12

      - name: Build WASM
        run: |
          emcmake cmake -B build_wasm
          emmake make -C build_wasm

      - name: Commit WASM output
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/tetweave_wasm.js docs/tetweave_wasm.wasm
          git diff --staged --quiet || git commit -m "ci: update WASM build"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git